apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: oe2eqofez-python 
  janus-idp.io/tekton: oe2eqofez-python
  backstage.io/kubernetes-id: oe2eqofez-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: oe2eqofez-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml