apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: oe2eqofez-python-gitops
  description: This is GitOps manifest for oe2eqofez-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=oe2eqofez-python
    backstage.io/kubernetes-id: oe2eqofez-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: oe2eqofez-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:oe2eqofez-python
